version: '3.8'
services:
  app:
    build: .
    container_name: daily-dose-budget
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/data/app.db
    volumes:
      - ./data:/data
