title: "Idea: <short title>"
labels: [idea]
body:
  - type: markdown
    attributes:
      value: "Have an idea? Let's discuss!"
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-liner of the idea
      placeholder: Add monthly trends chart
    validations:
      required: true
  - type: textarea
    id: detail
    attributes:
      label: Details
      description: Describe the idea and potential value
